name: Plasmo build chrome development relase
on:
  workflow_dispatch:
  push:
    # tags:
    #   - '*.*.*.*-*'
    branches: [plasmo]

jobs:
  build:
    # if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18.12.1 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
                 
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          # rm -rf node_modules/ pnpm-lock.yaml
          pnpm install
          pnpm install postcss@^8 webpack@^4.0.0

      - name: Build artifacts
        run: |
            npm run release && head -n10 CHANGELOG.md
            . action.sh
            git push --follow-tags origin HEAD

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/jiffyReader-*"
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: chrome ext upload
        run: npx cws-upload ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.REFRESH_TOKEN }} ./build/jiffyReader-chrome-development.zip ${{ secrets.EXTENSION_DEV_ID }}
