name: Plasmo build release
on:
  workflow_dispatch:
  push:
    # tags-ignore:
    #   - '*.*.*.*-*'
    branches: [master,plasmo]

jobs:
  build:
    # if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18.12.1 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
                 
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          # rm -rf node_modules/ pnpm-lock.yaml
          pnpm install
          pnpm install postcss@^8 webpack@^4.0.0

      - name: Build artifacts
        run: |
            git config --global user.email "gh-action@github.com"
            git config --global user.name "gh-action"

            npm run release
            make build@latest test print-manifests

      - name: Read version from package.json
        run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV

      - name: chrome ext upload
        run: |
          npx cws-upload ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.REFRESH_TOKEN }} ./build/jiffyReader-chrome-prod.zip ${{ secrets.EXTENSION_ID }}
          
          # if secrete.DEV_EXTENSION_ID is not empty then publish
          if [ -n "${{ secrets.EXTENSION_DEV_ID }}" ]; then
          npx cws-upload ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.REFRESH_TOKEN }} ./build/jiffyReader-chrome-dev.zip ${{ secrets.EXTENSION_DEV_ID }}
          fi

      # - name: WebExtPublish: Firefox
      #   uses: maoserr/firefox_extension_publish@v1.0.4
      #   with:
      #       firefox_extension_id: ${{ secrets.FIREFOX_DEV_EXT_ID }}
      #       api_key: ${{ secrets.FIREFOX_API_KEY }}
      #       api_secret: ${{ secrets.FIREFOX_API_SECRET }}
      #       file: build/jiffyReader-firefox-dev.xpi

      - uses: ncipollo/release-action@v1
        with:
          # artifacts: "dist/wyzant-looker.zip,dist/changelog.md,CHANGELOG.md"
          artifacts: "build/jiffyReader*"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ env.VERSION }}
          
      - name: push master tags
        run: git push --follow-tags origin HEAD

      - name: chrome ext publish
        run: |
          npx cws-publish ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.REFRESH_TOKEN }} ./build/jiffyReader-chrome-prod.zip ${{ secrets.EXTENSION_ID }}
          
          # if secrete.DEV_EXTENSION_ID is not empty then publish
          if [ -n "${{ secrets.EXTENSION_DEV_ID }}" ]; then
          npx cws-publish ${{ secrets.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ secrets.REFRESH_TOKEN }} ./build/jiffyReader-chrome-dev.zip ${{ secrets.EXTENSION_DEV_ID }}
          fi
          

